// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyAhJarBu7EQaq3u9TBhJOWE13K4KuIMY',
    appId: '1:222846896133:web:875a6aaa54383c4196b46c',
    messagingSenderId: '222846896133',
    projectId: 'datingapp-7d6d4',
    authDomain: 'datingapp-7d6d4.firebaseapp.com',
    storageBucket: 'datingapp-7d6d4.firebasestorage.app',
    measurementId: 'G-1D9GMDSGRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPH1QC_Tb5cAe_z8RTZntTxRuWK2t2UXA',
    appId: '1:222846896133:android:a6d556c0563f96b696b46c',
    messagingSenderId: '222846896133',
    projectId: 'datingapp-7d6d4',
    storageBucket: 'datingapp-7d6d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWSCuuJmV1Rw36mslP6Nn6KMixvMYgG4E',
    appId: '1:222846896133:ios:f89512d9ecc56e3996b46c',
    messagingSenderId: '222846896133',
    projectId: 'datingapp-7d6d4',
    storageBucket: 'datingapp-7d6d4.firebasestorage.app',
    iosBundleId: 'com.codemobi.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWSCuuJmV1Rw36mslP6Nn6KMixvMYgG4E',
    appId: '1:222846896133:ios:f89512d9ecc56e3996b46c',
    messagingSenderId: '222846896133',
    projectId: 'datingapp-7d6d4',
    storageBucket: 'datingapp-7d6d4.firebasestorage.app',
    iosBundleId: 'com.codemobi.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyAhJarBu7EQaq3u9TBhJOWE13K4KuIMY',
    appId: '1:222846896133:web:423390e13746ee0796b46c',
    messagingSenderId: '222846896133',
    projectId: 'datingapp-7d6d4',
    authDomain: 'datingapp-7d6d4.firebaseapp.com',
    storageBucket: 'datingapp-7d6d4.firebasestorage.app',
    measurementId: 'G-JKPH7C94QQ',
  );
}
